{% set version = "1.1.1" %}
{% set sha256 = "98cb1184bd53b9cb27ef88d1b8f3f282a328760357281c402d4c53ac277d1c6b" %}

package:
  name: qgrid
  version: {{ version }}

source:
  fn: qgrid-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/q/qgrid/qgrid-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - notebook >=4.0.0
  run:
    - python
    - notebook >=4.0.0
    - pandas >=0.17.0
    - ipywidgets >=7.0.0

test:
  imports:
    - qgrid
    - qgrid.tests

about:
  home: https://github.com/quantopian/qgrid
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pandas DataFrame viewer for Jupyter Notebook
  description: |
    Qgrid is a Jupyter notebook widget which uses SlickGrid to render pandas DataFrames.
    This allows you to explore your DataFrames with intuitive scrolling, sorting, and
    filtering controls, as well as edit your DataFrames by double clicking cells.
  doc_url: http://qgrid.readthedocs.org/en/latest/
  doc_source_url: https://github.com/quantopian/qgrid/blob/master/docs/index.rst
  dev_url: https://github.com/quantopian/qgrid

extra:
  recipe-maintainers:
    - TimShawver
    - alen12345
