travis:
  secure:
    BINSTAR_TOKEN: fxZAxNFAgIZB0iGg76datfZcnvzycQ6WOXN+VvwhnaecGyzLlQmza8GHRGzkXBM4njVzRffiE1md6WQ3gLgf3MhTnI8U1E+E7tPlROQJ6VdNHo61XCQuRh8wepvoTcs0S9dzlPqoMxNcOwotpwkzyU5+iMdXYdiQMs/hyNYcyhCz0Cr2TR1//7FKm6Ys5g1/FsFR0CwDpjTWio5pTOpFvUPt1ZFH8ZPNN+Tn5sZcXAjabUiMA/ugoK/V81tvrm7RZoIqHdpeFujDx7/pSr7xU3Us+ufd6OnyYxUThSjIjHdFBdYhpAF2r2u5mSZeoTkNL4Nq1tWo+Oj2HX0GdmI5tsrnoWUmyeJVil7NmS4KmDTiPfvaxbBpNBS6XncdveDyVROMpz6lN6eODNK3jK2iQ1/exPOQiHcLmPt9gFOpESZMl+RWeIZlFDoYxDHheDjXdS9EntsrRgB65+uqJM0RqgI9CgAJ4OX6Zs4hw/WURlMbOqTWRN55zhANMRDXAP4n2Or/96gk0kFyReXy2DXwsGfwqapdYHLeRPcdE9WnNhERPyKI2oa7+Nk5W07+TE10F/5N/7Lcx93pURtjVVkHXlCeJIJdjgsLhr7y6sewiGUj8EC67Lw71Pr0RUXh/4pokI5skbwpElStnxCrAume2hVJ7ATDvDnjN83Fzbnvx0o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
